# -*- coding: utf-8 -*-
"""stable_diffusion (4).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pwUIS8dlC2qXfA-h9hLMJNfVYIUL7dHs
"""

import PIL
import requests
import torch
from io import BytesIO
from diffusers import StableDiffusionInpaintPipeline
pipeline = StableDiffusionInpaintPipeline.from_pretrained(
        "runwayml/stable-diffusion-inpainting",torch_dtype=torch.float16,)

pipeline = pipeline.to("cuda")

from PIL import Image
mask_image= Image.open("./mask_plot.png")
raw_image=Image.open("./std_imgs/S_BD/n02843553_1362.JPEG")

mask_image

raw_image

import matplotlib.pyplot as plt 
import requests
from io import BytesIO
import torch
import torchvision.transforms as T 

tensor = mask_image
image_tensors=T.ToTensor()(mask_image)
image_tensors

transform = T.ToPILImage()
mask_image= transform(image_tensors).resize((512,512))
init_image= raw_image.resize((512,512))

prompt = "remove the squirrel and fill it with the backgroud col"
image1 = pipeline(prompt=prompt,image=init_image, mask_image=mask_image).images[0]
plt.imshow(image1)
plt.savefig('./std_imgs/Gnd_imgs/18')

def replace_birds(input_image_path, output_image_path):
    # Open input image and mask
    input_image = Image.open(input_image_path).resize((512, 512))
    mask_image = Image.open("./mask_plot.png").resize((512, 512))
    prompt = "remove the object in the mask area and replace with an eagle"
    output_image = pipeline(prompt=prompt, image=input_image, mask_image=mask_image).images[0]
    output_image.save(output_image_path)
input_image_filenames = [
    "./std_imgs/S_BD/n02843553_1362.JPEG",
    "./std_imgs/S_BD/n02843553_2568.JPEG",
    "./std_imgs/S_BD/n02843553_2686.JPEG",
    "./std_imgs/S_BD/n02843553_4181.JPEG",
    "./std_imgs/S_BD/n02843553_4896.JPEG"
]
for input_filename in input_image_filenames:
    for i in range(10):
        output_filename = input_filename[:-4] + f"-andBirdsReplaced-{i}.jpg"   
        replace_birds(input_filename, output_filename)

