# -*- coding: utf-8 -*-
"""generateBirdFeederImagesFromText.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kbq3qY-LTJh5ex1It0QmbXi-jBFPDKhz
"""

from diffusers import StableDiffusionPipeline
import torch

model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

prompt = "a photo of bird looking at a birdfeeder"
image = pipe(prompt).images[0]  
    
image.save("bird_and_birdfeeder.png")

